<?php

/**
 * -------------------------------------------------------------------------
 * favorites plugin for GLPI
 * -------------------------------------------------------------------------
 *
 * GPLv3 License
 *
 * Copyright (C) 2026  Thierry Brouard
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * -------------------------------------------------------------------------
 * @copyright Copyright (C) 2026 by the favorites plugin team.
 * @license   GPL-3.0 https://opensource.org/license/gpl-3.0
 * @link      https://github.com/brouardt/glpi-plugin-favorite
 * -------------------------------------------------------------------------
 */

namespace GlpiPlugin\Favorites;

use CommonDBTM;
use CommonGLPI;
use Glpi\Application\View\TemplateRenderer;
use Session;
use Toolbox;


class Preference extends CommonDBTM
{
//    public static $rightname = 'plugin_favorites';
    public static $rightname = 'dropdown';
    public $can_be_translated = true;

    public static function getIndexName()
    {
        return 'users_id';
    }

    public static function getTypeName($nb = 0)
    {
        return __s('Favorites', PLUGIN_FAVORITES);
    }

    public static function getIcon()
    {
        return 'ti ti-heart'; // TODO: Change the autogenerated stub
    }

    public function rawSearchOptions()
    {
        $tab = [];

        $tab[] = [
            'id' => 'common',
            'name' => self::getTypeName(2),
        ];

        $tab[] = [
            'id' => '2',
            'table' => $this->getTable(),
            'field' => 'types',
            'name' => _n('Type', 'Types', 2),
            'datatype' => 'dropdown',
        ];

        return $tab;
    }

    public static function showPreferences()
    {
        $preference = new Preference();
        $preference->getFromDB(Session::getLoginUserID());

        $can_edit = ($preference->getField('users_id') == Session::getLoginUserID());
        if (!$can_edit) {
            return false;
        }

        // compose multiple choice menu
        $menu = $_SESSION['glpimenu'];
        $list = [];
        foreach ($menu as $item => $object) {
            if (!empty($object['types'])) {
                foreach ($object['types'] as $type) {
                    if (!empty($type)
                        && isset($object['content'][strtolower($type)]['title'])
                        && !empty($object['content'][strtolower($type)]['title'])
                    ) {
                        $list[$object['title']][$type] = $object['content'][strtolower($type)]['title'];
                    }
                }
            }
        }

        TemplateRenderer::getInstance()->display('@favorites/preference.html.twig', [
            'action' => Toolbox::getItemTypeFormURL(self::class),
            'item' => $preference,
            'menus' => $list,
            'types' => json_decode($preference->getField('types')),
            'canedit' => $can_edit
        ]);
    }


    /**
     * @param CommonGLPI $item
     * @param $withtemplate
     * @return string|string[]
     */
    public function getTabNameForItem(CommonGLPI $item, $withtemplate = 0)
    {
        if (($item->getType() == 'Preference')) {
            return self::createTabEntry(self::getTypeName(), 0, $item::getType(), self::getIcon());
        }
        return '';
    }

    /**
     * @param CommonGLPI $item
     * @param $tabnum
     * @param $withtemplate
     * @return true
     */
    public static function displayTabContentForItem(CommonGLPI $item, $tabnum = 1, $withtemplate = 0)
    {
        if ($item->getType() == 'Preference') {
            self::showPreferences();
        }

        return true;
    }

    /**
     * @return array
     */
    public static function getFavoritesTypes()
    {
        $preference = new Preference();
        $preference->getFromDB(Session::getLoginUserID());

        $types = $preference->getField('types');

        $list = [];
        if ($types) {
            $list = json_decode($types);
        }

        return $list;
    }
}
